In [9]:
import numpy as np
import pandas as pd

In [15]:
df = pd.DataFrame({
    "date" : pd.date_range('2026-01-01',periods=20),
    "product": ['a','b','c','d']*5,
    "region":['east','west','south','north','east','west','south','north','east','west','south','north','east','west','south','north','east','west','south','north'],
    "sales": np.random.randint(100,1000,20),
    "units": np.random.randint(10,100,20),
    "Rep": ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']

})

In [11]:
df

         date product region  sales  units    Rep
0  2026-01-01       a   east    215     23   John
1  2026-01-02       b   west    937     22   Mary
2  2026-01-03       c  south    115     12    Bob
3  2026-01-04       d  north    378     56  Alice
4  2026-01-05       a   east    479     18   John
5  2026-01-06       b   west    567     77   Mary
6  2026-01-07       c  south    539     12    Bob
7  2026-01-08       d  north    253     83  Alice
8  2026-01-09       a   east    969     43   John
9  2026-01-10       b   west    215     85   Mary
10 2026-01-11       c  south    587     69    Bob
11 2026-01-12       d  north    100     84  Alice
12 2026-01-13       a   east    639     23   John
13 2026-01-14       b   west    577     42   Mary
14 2026-01-15       c  south    995     63    Bob
15 2026-01-16       d  north    210     10  Alice
16 2026-01-17       a   east    784     65   John
17 2026-01-18       b   west    725     30   Mary
18 2026-01-19       c  south    459     35    Bob
19 2026-01-20       d  north    819     68  Alice

In [17]:
df['month']=df['date'].dt.month_name()
df['quarter']='Q'+ df['date'].dt.quarter.astype(str)
df

         date product region  sales  units    Rep    month quarter
0  2026-01-01       a   east    737     31   John  January      Q1
1  2026-01-02       b   west    814     95   Mary  January      Q1
2  2026-01-03       c  south    727     10    Bob  January      Q1
3  2026-01-04       d  north    710     34  Alice  January      Q1
4  2026-01-05       a   east    625     85   John  January      Q1
5  2026-01-06       b   west    261     66   Mary  January      Q1
6  2026-01-07       c  south    816     11    Bob  January      Q1
7  2026-01-08       d  north    889     25  Alice  January      Q1
8  2026-01-09       a   east    843     16   John  January      Q1
9  2026-01-10       b   west    205     70   Mary  January      Q1
10 2026-01-11       c  south    334     46    Bob  January      Q1
11 2026-01-12       d  north    677     76  Alice  January      Q1
12 2026-01-13       a   east    933     85   John  January      Q1
13 2026-01-14       b   west    714     53   Mary  January      Q1
14 2026-01-15       c  south    841     12    Bob  January      Q1
15 2026-01-16       d  north    606     11  Alice  January      Q1
16 2026-01-17       a   east    447     97   John  January      Q1
17 2026-01-18       b   west    873     29   Mary  January      Q1
18 2026-01-19       c  south    589     44    Bob  January      Q1
19 2026-01-20       d  north    572     30  Alice  January      Q1

In [19]:
pivot_table1 = pd.pivot_table(df,values='sales',index='region',columns='product')
print(pivot_table1)

product      a      b      c      d
region
east     717.0    NaN    NaN    NaN
north      NaN    NaN    NaN  690.8
south      NaN    NaN  661.4    NaN
west       NaN  573.4    NaN    NaN

In [28]:
pivot_table2 = pd.pivot_table(df,values='sales',index = 'region',columns = 'product',aggfunc = 'max')
print(pivot_table2)

product      a      b      c      d
region
east     933.0    NaN    NaN    NaN
north      NaN    NaN    NaN  889.0
south      NaN    NaN  841.0    NaN
west       NaN  873.0    NaN    NaN

In [29]:
pivot_table3 = pd.pivot_table(df,values=['sales','units'],index='region',columns='product',aggfunc='median')
print(pivot_table3)

         sales                      units
product      a      b      c      d     a     b     c     d
region
east     737.0    NaN    NaN    NaN  85.0   NaN   NaN   NaN
north      NaN    NaN    NaN  677.0   NaN   NaN   NaN  30.0
south      NaN    NaN  727.0    NaN   NaN   NaN  12.0   NaN
west       NaN  714.0    NaN    NaN   NaN  66.0   NaN   NaN

In [31]:
pd.crosstab(df['region'],df['sales'])

sales,205,261,334,447,572,589,606,625,677,710,714,727,737,814,816,841,843,873,889,933
region,,,,,,,,,,,,,,,,,,,,
east,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,1
north,0,0,0,0,1,0,1,0,1,1,0,0,0,0,0,0,0,0,1,0
south,0,0,1,0,0,1,0,0,0,0,0,1,0,0,1,1,0,0,0,0
west,1,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0